import Head from 'next/head'
import { useEffect, useState } from 'react'
import Logo from '../components/Logo/Logo'
import Spinner from '../components/Spinner/Spinner'
import styles from '../styles/Home.module.css'
import axios from 'axios'

export default function Home() {
  const [data, setData] = useState()
  const [city, setCity] = useState('lagos')

  useEffect(() => {
    getData()
  },[])

  //Fetch weather data
  const getData = async () => {
    try {
      setData()
      const res = await axios.get(`https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=a4346ea37667531d5a0e26fa8a930037`)
      setData(res)
    } catch (err) {
      setData(null)
    }    
  }

  return (
    <div>
      <Head>
        <title>myWeather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{maxWidth: '500px', width: '100%', height: '100vh', padding: '4rem 2rem', backgroundColor: '#80808019', margin: '0 auto'}}>
          <Logo/>
          <div style={{display: 'flex', alignItems: 'center', position: 'relative', marginBottom: '1rem'}}>
            <input type='text' name='location' id='location' placeholder='Search city' onChange={(e) => setCity(e.target.value)}/>
            <div style={{border: '1px solid orange', padding: '.5rem 1rem', backgroundColor: 'orange', fontSize: '1rem', position: 'absolute', cursor: 'pointer', right: 0}} onClick={() => getData()}>Submit</div>
          </div>

          {
            data === null ? <div style={{textAlign: 'center'}}>City not found</div> :
            data === undefined ? <Spinner/> : 
            <List
              temp={(data?.data?.main?.temp-273.15).toFixed()}
              city={data?.data?.name}
              src={data?.data?.weather[0]?.icon}
              alt={data?.data?.weather[0]?.description}
              max={(data?.data?.main?.temp_max-273.15).toFixed()}
              min={(data?.data?.main?.temp_min-273.15).toFixed()}
            />
          }
          
          <h3>Upcoming days</h3>
        </div>
      </main>
    </div>
  )
}

const List = ({ temp, city, src, alt, max, min }) => {
  return(
    <div>
      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between'}}>
        <div style={{display: 'flex', alignItems: 'center', fontSize: '1.5rem'}}>
          <div style={{display: 'flex', alignItems: 'center'}}>
          <div style={{marginRight: '.3rem'}}>{temp}<sup>o</sup>c</div>
            <div style={{marginRight: '1rem'}}>
              <div style={{fontSize: '.8rem', marginBottom: '.5rem'}}>max-{max}</div>
              <div style={{fontSize: '.8rem'}}>min-{min}</div>
            </div>  
          </div>
        </div>
        <div style={{alignSelf: 'end'}}>
          <img src={`http://openweathermap.org/img/wn/${src}@2x.png`} width='100px' height='100px' alt={alt} />
        </div>
      </div>
      
      
      <div style={{textAlign: 'end', marginRight: '1rem'}}>{city}</div>
    </div>
  )
}